services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - tung-sahur:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  tung-sahur: {}
